web:
  build: .
  command: nodemon --harmony server.js
  working_dir: /var/www
  volumes:
    - .:/var/www/
  ports:
   - "3000:3000"
  env_file:
    - ./envvars
  links:
   - postgres
  environment:
    DATABASE_URL: postgres://postgres:@postgres:5432/postgres

postgres:
    image: postgres:9.4
